const APP_NAME: string = "BROWSER_HUB";
export const CURRENT_VERSION_APP = "0.0.1";

export const LOCAL_STORAGE_KEYS: {
    APP: typeof APP_NAME;
    THEME_COLOR: `${typeof APP_NAME}.THEME_COLOR`;
    THEME_MODE: `${typeof APP_NAME}.THEME_MODE`;
    SHOW_ICONS_THEME_SETTING: `${typeof APP_NAME}.SHOW_ICONS_THEME_SETTING`;
    RELEASE_VERSION: `${typeof APP_NAME}.RELEASE_VERSION`,
} = {
    APP: APP_NAME,
    THEME_COLOR: `${APP_NAME}.THEME_COLOR`,
    THEME_MODE: `${APP_NAME}.THEME_MODE`,
    SHOW_ICONS_THEME_SETTING: `${APP_NAME}.SHOW_ICONS_THEME_SETTING`,
    RELEASE_VERSION: `${APP_NAME}.RELEASE_VERSION`,
};
